#!/bin/bash

set -e

ROCM_PATH="/opt/rocm"
INSTALL_PATH="${ROCM_PATH}/hcfft"
LIBRARY_DIR="${INSTALL_PATH}/lib"
COMMON_LIB="${ROCM_PATH}/lib"
SYMLINK_DIR="${ROCM_PATH}/hipfft"

rm_symlink() {
    rm -rf ${COMMON_LIB}/libhipfft.so
    rm -rf /opt/rocm/lib/libhcfft.so
    rm -rf ${SYMLINK_DIR}
}

rm_ldconfig() {
    rm -rf ${INSTALL_PATH}
    rm -f /etc/ld.so.conf.d/hcfft-rocm-dev.conf && ldconfig
}

case "$1" in
   remove)
       rm_symlink
       rm_ldconfig
   ;;
   purge)
   ;;
   *)
       exit 0
   ;;
esac

